<h1>Add a meetup</h1>

<?php
    $form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($form->get('title')->setAttribute('class', 'form-control')) ?>

<?= $this->formRow($form->get('description')->setAttribute('class', 'form-control')) ?>

<?= $this->formRow($form->get('datedebut')->setAttribute('class', 'form-control')) ?>

<?= $this->formRow($form->get('datefin')->setAttribute('class', 'form-control')) ?>

<?= $this->formInput($form->get('submit')->setAttribute('class', 'btn btn-primary')) ?>

<?= $this->form()->closeTag($form); ?>
