<h1>Add a meetup</h1>

<?php
    $form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($form->get('title')) ?>

<?= $this->formRow($form->get('description')) ?>

<?= $this->formRow($form->get('datedebut')) ?>

<?= $this->formRow($form->get('datefin')) ?>

<?= $this->formInput($form->get('submit')) ?>

<?= $this->form()->closeTag($form); ?>
