<h1>Edit</h1>

<?php
$form = $this->form;
?>
<?= $this->form()->openTag($form); ?>
<?= $this->formRow($form->get('title')->setAttribute('class', 'form-control')); ?>
<br>
<?= $this->formRow($form->get('description')->setAttribute('class', 'form-control')); ?>
<br>
<?= $this->formRow($form->get('datedebut')->setAttribute('class', 'form-control')); ?>
<br>
<?= $this->formRow($form->get('datefin')->setAttribute('class', 'form-control')); ?>
<br>
<?= $this->formInput($form->get('submit')->setAttribute('class', 'btn btn-primary')) ?>
<?= $this->form()->closeTag($form); ?>

