<h1>Meetups</h1>

<table class="table">
    <thead>
    <tr>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Date de debut</th>
        <th scope="col">Date de fin</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->meetups as $meetup): /* @var $meetup \Meetup\Entity\Meetup */
    ;?>
    <tr>
        <td><?= $meetup->getTitle();  ?></td>
        <td><?= $meetup->getDescription(); ?></td>
        <td><?= $meetup->getDatedebut()->format('Y-m-d'); ?></td>
        <td><?= $meetup->getDatefin()->format('Y-m-d'); ?></td>
        <td> <a class="btn btn-info" href="<?= $this->url('meetups/edit', ['id' => $meetup->getId()]); ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
           </td>
        <td><form action="<?php echo $this->url('meetups/delete'); ?>" method="post">
                <input type="hidden" name="id" value="<?php echo $meetup->getId(); ?>">
                <button class="btn btn-danger" type="submit"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></button>
            </form></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<a href="<?= $this->url('meetups/add'); ?>" class="btn btn-primary">Add new</a>




